services:
  aodata-db-tool:
    container_name: aodata-db-tool
    build:
      context: .
      dockerfile: Dockerfile
    volumes: 
      - ./data:/data
    restart: unless-stopped
    depends_on:
      - aodata-db